"""Token-health probe CLI — invoked from cron / launchd.

Plan §3.4.1.  Run with ``python -m schwab_marketdata_mcp.health``.

Exit codes (plan §3.2.2.1 / §3.4.1):

    0 — healthy
    1 — expires_in < 24 h (warn)
    2 — expires_in < 12 h **or** already expired (error; cron MAILTO triggers)
    3 — TokenState.MISSING
    4 — TokenState.MALFORMED
    5 — TokenState.INSECURE_PERMS

Side-effects:
    * Writes/overwrites ``~/Desktop/SCHWAB_REAUTH_NEEDED.md`` for any non-zero exit.
    * Best-effort desktop notification (osascript on macOS, notify-send on Linux).
    * Truncates ``usage.jsonl`` to the rolling 30-day window.
    * Emits one line of structured JSON to stderr.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Final

from .errors import SchwabAuthError, redact_secrets
from .metrics import DEFAULT_RETENTION_DAYS, truncate_to_window, usage_path
from .security import (
    TokenState,
    check_token_file_state,
    enforce_token_perms,
    insecure_perms_hint,
    resolve_token_path,
)

# Token validity window (days).  Schwab refresh token lifetime ≈ 7 days.
REFRESH_TOKEN_LIFETIME_DAYS: Final[int] = 7
WARN_THRESHOLD = timedelta(hours=24)
CRITICAL_THRESHOLD = timedelta(hours=12)
DESKTOP_REAUTH_FILE: Final[str] = "SCHWAB_REAUTH_NEEDED.md"


# ---------------------------------------------------------------------------
# Result enum
# ---------------------------------------------------------------------------


class HealthExit:
    HEALTHY = 0
    EXPIRES_24H = 1
    EXPIRED_OR_12H = 2
    MISSING = 3
    MALFORMED = 4
    INSECURE_PERMS = 5


# ---------------------------------------------------------------------------
# Public helpers (testable; CLI logic stays thin)
# ---------------------------------------------------------------------------


def compute_expires_in(creation_ts: float, *, now_ts: float | None = None) -> timedelta:
    """Time-to-expiry from a token's creation timestamp (seconds since epoch)."""
    now = now_ts if now_ts is not None else datetime.now(tz=UTC).timestamp()
    age = timedelta(seconds=max(0.0, now - creation_ts))
    lifetime = timedelta(days=REFRESH_TOKEN_LIFETIME_DAYS)
    return lifetime - age


def classify(expires_in: timedelta) -> int:
    """Map a time-to-expiry to one of the HealthExit codes."""
    if expires_in <= timedelta(0):
        return HealthExit.EXPIRED_OR_12H
    if expires_in < CRITICAL_THRESHOLD:
        return HealthExit.EXPIRED_OR_12H
    if expires_in < WARN_THRESHOLD:
        return HealthExit.EXPIRES_24H
    return HealthExit.HEALTHY


def human_summary(exit_code: int, expires_in: timedelta | None) -> str:
    """One-line summary suitable for desktop notification + log."""
    if exit_code == HealthExit.HEALTHY:
        assert expires_in is not None
        hours = int(expires_in.total_seconds() // 3600)
        return f"Schwab MCP: token healthy, expires in ~{hours}h"
    if exit_code == HealthExit.EXPIRES_24H:
        assert expires_in is not None
        hours = int(expires_in.total_seconds() // 3600)
        return f"Schwab MCP: token expires in {hours}h — please reauthorize soon"
    if exit_code == HealthExit.EXPIRED_OR_12H:
        return "Schwab MCP: token expired or <12h left — run auth login_flow"
    if exit_code == HealthExit.MISSING:
        return "Schwab MCP: token not initialized — run auth login_flow"
    if exit_code == HealthExit.MALFORMED:
        return "Schwab MCP: token file corrupted — back it up and re-run auth"
    if exit_code == HealthExit.INSECURE_PERMS:
        return "Schwab MCP: token file has insecure permissions — chmod 600"
    return f"Schwab MCP: unknown state ({exit_code})"


# ---------------------------------------------------------------------------
# Notification side channels (best-effort)
# ---------------------------------------------------------------------------


def _write_desktop_marker(message: str, *, hint: str = "") -> Path | None:
    """Write ``~/Desktop/SCHWAB_REAUTH_NEEDED.md``.  Returns the path on success."""
    desktop = Path.home() / "Desktop"
    if not desktop.exists():
        return None
    target = desktop / DESKTOP_REAUTH_FILE
    body = (
        "# Schwab MCP — Reauthorize required\n\n"
        f"_Generated by `schwab_marketdata_mcp.health` at "
        f"{datetime.now(tz=UTC).isoformat(timespec='seconds')}_\n\n"
        f"## Status\n\n{message}\n\n"
    )
    if hint:
        body += f"## Hint\n\n```\n{redact_secrets(hint)}\n```\n\n"
    body += (
        "## What to do next\n\n"
        "1. Open a terminal in your `schwab-marketdata-mcp` checkout.\n"
        "2. Run:\n\n"
        "   ```bash\n"
        "   uv run python -m schwab_marketdata_mcp.auth login_flow\n"
        "   ```\n\n"
        "3. After the browser flow completes, this file will be regenerated\n"
        "   on the next health probe with a healthy status.\n"
    )
    try:
        target.write_text(body, encoding="utf-8")
    except OSError:
        return None
    return target


def _notify(message: str) -> None:
    """Fire a best-effort desktop notification — never raises."""
    if sys.platform == "darwin":
        osa = shutil.which("osascript")
        if osa:
            try:
                subprocess.run(
                    [
                        osa,
                        "-e",
                        f'display notification "{message}" with title "Schwab MCP" sound name "Sosumi"',
                    ],
                    check=False,
                    timeout=5,
                )
            except (OSError, subprocess.SubprocessError):
                pass
        return
    if sys.platform.startswith("linux"):
        ns = shutil.which("notify-send")
        if ns:
            try:
                subprocess.run(
                    [ns, "-u", "critical", "Schwab MCP", message],
                    check=False,
                    timeout=5,
                )
            except (OSError, subprocess.SubprocessError):
                pass
        return


def _emit_stderr(record: dict[str, object]) -> None:
    sys.stderr.write(json.dumps(record, separators=(",", ":")) + "\n")
    sys.stderr.flush()


# ---------------------------------------------------------------------------
# Token-age probe with primary + fall-back paths
# ---------------------------------------------------------------------------


def _probe_token_age_via_schwab_py(token_path: Path) -> timedelta | None:
    """Primary path — call ``schwab.client.Client.token_age()``.

    Plan §3.2.2 mandates schwab-py's public API for the main path.  Returns
    ``None`` if the call fails (caller falls back to mtime).
    """
    api_key = os.environ.get("SCHWAB_APP_KEY")
    app_secret = os.environ.get("SCHWAB_APP_SECRET")
    callback = os.environ.get("SCHWAB_CALLBACK_URL", "https://127.0.0.1:8182")
    if not api_key or not app_secret or api_key == "dummy-not-a-real-secret":
        return None
    try:
        from schwab.auth import easy_client

        # ``interactive=False`` ensures health probe never opens a browser.
        client = easy_client(
            api_key=api_key,
            app_secret=app_secret,
            callback_url=callback,
            token_path=str(token_path),
            asyncio=False,
            enforce_enums=True,
            interactive=False,
        )
        age = client.token_age()
        if isinstance(age, timedelta):
            return timedelta(days=REFRESH_TOKEN_LIFETIME_DAYS) - age
    except Exception:
        return None
    return None


def _probe_token_age_via_mtime(token_path: Path) -> timedelta | None:
    """Fall-back — read the file mtime.  Plan §3.2.2 (degraded mode)."""
    try:
        mtime = token_path.stat().st_mtime
    except OSError:
        return None
    age = datetime.now(tz=UTC).timestamp() - mtime
    return timedelta(days=REFRESH_TOKEN_LIFETIME_DAYS) - timedelta(seconds=max(0.0, age))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def run(token_path_arg: str | None = None) -> int:
    """Run the health probe and return the exit code."""
    try:
        token_path = resolve_token_path(token_path_arg)
    except SchwabAuthError as exc:
        _emit_stderr({"event": "health_path_rejected", "reason": exc.reason, "hint": exc.hint})
        _write_desktop_marker(human_summary(HealthExit.MISSING, None), hint=exc.hint)
        _notify(human_summary(HealthExit.MISSING, None))
        return HealthExit.MISSING

    state, _parsed = check_token_file_state(token_path)

    if state is TokenState.MISSING:
        msg = human_summary(HealthExit.MISSING, None)
        _emit_stderr({"event": "health", "state": "missing", "path": str(token_path)})
        _write_desktop_marker(msg)
        _notify(msg)
        # Truncate even on missing: keeps usage.jsonl from growing forever
        # if the user paused the project before reauthorising.
        try:
            truncate_to_window(days=DEFAULT_RETENTION_DAYS)
        except OSError:
            pass
        return HealthExit.MISSING

    if state is TokenState.INSECURE_PERMS:
        actual = os.stat(token_path).st_mode & 0o7777
        hint = insecure_perms_hint(token_path, actual)
        msg = human_summary(HealthExit.INSECURE_PERMS, None)
        _emit_stderr({"event": "health", "state": "insecure_perms", "actual_mode": oct(actual)})
        _write_desktop_marker(msg, hint=hint)
        _notify(msg)
        return HealthExit.INSECURE_PERMS

    if state is TokenState.MALFORMED:
        msg = human_summary(HealthExit.MALFORMED, None)
        _emit_stderr({"event": "health", "state": "malformed", "path": str(token_path)})
        _write_desktop_marker(msg)
        _notify(msg)
        return HealthExit.MALFORMED

    # state is VALID — defense in depth: also enforce perms (raises if drifted)
    try:
        enforce_token_perms(token_path)
    except SchwabAuthError as exc:
        _emit_stderr({"event": "health", "state": "insecure_perms_recheck", "hint": exc.hint})
        _write_desktop_marker(human_summary(HealthExit.INSECURE_PERMS, None), hint=exc.hint)
        _notify(human_summary(HealthExit.INSECURE_PERMS, None))
        return HealthExit.INSECURE_PERMS

    # Truncate usage.jsonl now that we know the path exists & is healthy.
    try:
        kept = truncate_to_window(days=DEFAULT_RETENTION_DAYS, path=usage_path())
    except OSError as exc:
        _emit_stderr({"event": "metrics_truncate_failed", "error": str(exc)})
        kept = -1

    # Probe token age — primary path (schwab-py) → fall-back (mtime).
    expires_in = _probe_token_age_via_schwab_py(token_path)
    probe_path = "schwab_py"
    if expires_in is None:
        expires_in = _probe_token_age_via_mtime(token_path)
        probe_path = "mtime_fallback"
    if expires_in is None:
        # Both paths failed — treat as worst-case (12 h critical).
        _emit_stderr({"event": "health", "state": "probe_failed"})
        _write_desktop_marker(human_summary(HealthExit.EXPIRED_OR_12H, None))
        _notify(human_summary(HealthExit.EXPIRED_OR_12H, None))
        return HealthExit.EXPIRED_OR_12H

    code = classify(expires_in)
    _emit_stderr(
        {
            "event": "health",
            "state": "probed",
            "probe_path": probe_path,
            "expires_in_seconds": int(expires_in.total_seconds()),
            "exit_code": code,
            "metrics_kept": kept,
        }
    )

    msg = human_summary(code, expires_in)
    if code != HealthExit.HEALTHY:
        _write_desktop_marker(msg)
        _notify(msg)
    return code


def cli_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="schwab_marketdata_mcp.health")
    parser.add_argument(
        "--config-dir",
        type=str,
        default=None,
        help="Override token directory (subject to allow-list — see security.py).",
    )
    args = parser.parse_args(argv)
    token_arg: str | None = None
    if args.config_dir:
        token_arg = str(Path(args.config_dir) / "token.json")
    return run(token_arg)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(cli_main())
